task_id: T-018
name: 生信论文模板拆解
phase: digestion
goal: goal_template_paper_digestion
project: P-012
objective: '为t012 的交付物d013里记录的每篇论文建立单独的拆解md讲解。

  每一篇单独一个md。要有总的html最后汇总。


  不需要先考虑对我项目本身启迪。


  而是讲解每一篇的介绍写作逻辑。结果写作逻辑。图的摆放逻辑


  注意这是mdpi杂志不是什么好杂志。我们说学习不是说他们多好多科学。而是对齐genes喜欢的风格以及工作量设置。不要用nature或者大sci标准理解它们。


  这里其实是开始归纳我们写作的参考模板了

  '
executor: hybrid
agent_id: null
config_agent_id: null
check_agent_id: null
execute_agent_id: null
server_id: null
status: done
cyhex_version: 1.1.3
created: '2026-06-23'
started: null
completed: '2026-06-22'
notes: 生信论文模板拆解
fast_pass_permission: yellow
sub_status: ''
fast_pass_last_auto_approved: check_review
fast_pass_last_auto_approved_at: '2026-06-23T03:43:48'
