task_id: T-021
name: standard_resources_optimal_formats
phase: development
goal: goal_precomputed_data_exploration
project: P-012
objective: '基于整理的预处理数据。从里面指出后续pxfquery的严格输入或者说内置的标准资源以及它们的最优格式，

  可以从里面提取。

  因为h5ad是一个符合格式而且是给单细胞准备的，

  我们准备数据尽可能小。


  最后是不是能给我。


  尤其是不是几个独立表格，浮点数是不是降低


  本任务输出将作为后续开发与测试的标准资源。所以交付需要小心加全。


  每一个资源都应该python检验过确认


  并且有详细介绍。'
executor: hybrid
agent_id: null
config_agent_id: null
check_agent_id: null
execute_agent_id: null
server_id: null
status: done
cyhex_version: 1.2.1
created: '2026-06-23'
started: null
completed: '2026-06-23'
notes: 标准资源最优格式整理
fast_pass_permission: yellow
sub_status: ''
fast_pass_last_auto_approved: check_review
fast_pass_last_auto_approved_at: '2026-06-23T04:42:43'
